version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  letsencrypt: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: navoica_enroll_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - .envs/.production/.django
      - .envs/.production/.postgres

    volumes:
      - ./external_static:/app/external_static
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: navoica_enroll_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - .envs/.production/.postgres

  nginx:
    restart: always
    image: staticfloat/nginx-certbot
    ports:
      - 81:81/tcp
      - 80:80/tcp
      - 443:443/tcp
    environment:
      ENVSUBST_VARS: DOMAIN
    env_file:
      - .envs/.production/.django
    depends_on:
      - django
    volumes:
      - ./compose/production/nginx:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt

  redis:
    image: redis:5.0


